### ISSUE TITLE
Module parse failed: Unexpected token (71:71)

### ISSUE THREAD

**Issue by spiritonline** [dagda1/cuttingedge#17]
Hi,

Im in the process of learning react and was looking at your [react-abortable-fetch](https://github.com/dagda1/cuttingedge/tree/main/packages/react-abortable-fetch) package. 
I was running into the issue of not being able to run my own useFetch from inside a loop and it seems your package has a way around that. However if I install in a create react app using: npm install @cutting/react-abortable-fetch and then import it I get the error below of which I have no clue on how to handle. 

Could you maybe point me in right direction? 
Much appreciated! (apologies if this was a stupid question)

-----------
./node_modules/@cutting/react-abortable-fetch/dist/react-abortable-fetch.esm.js 71:71
Module parse failed: Unexpected token (71:71)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| class D extends Error {
|   constructor(t = "", r, e, o) {
>     super(t), this.status = r, this.body = e, this.bodyParseError = o ?? null;
|   }
|

**Comment by dagda1** [comment]
@spiritonline thank you for reporting this.  This is definitely not a silly question.  I will take a look and get back to you

**Comment by spiritonline** [comment]
Thanks for the swift response! Looking forward to hearing more.

**Comment by dagda1** [comment]
@spiritonline I can see what it is.  It is outputting the nullish coalescing operator `??` in the compiled output

```js
super(t), this.status = r, this.body = e, this.bodyParseError = o ?? null;
```

I'll get a fix out this afternoon

**Comment by spiritonline** [comment]
Amazing! Thank you.

**Comment by dagda1** [comment]
@spiritonline thank you so much for raising this.  You unearthed a whole pile of problems with my rollup setup.

I have fixed this in #18 and version `0.9.4`

```json
"@cutting/react-abortable-fetch": "^0.9.4",
```

Please let me know if you find any other issues

**Comment by spiritonline** [comment]
All looks good now. Many thanks again for your swift response. Looking forward to using this package!

**Comment by dagda1** [comment]
@spiritonline strangely, things do not often work as well outside of my laptop so your feedback is greatly appreciated.

I had no idea those bugs existed.
