### ISSUE TITLE
@cutting/hooks relies on react-router for `useLocation`

### ISSUE THREAD

**Issue by joeyfigaro** [dagda1/cuttingedge#259]
Thank you for authoring your approach and work! 

**Describe the bug**
I'm working on building out a UI kit and am wrapping up responsive SVGs. We're running into issues with `@cutting/svg` / `@cutting/hooks` because of the dependence on `react-router`. It looks like `useScrollToTop` imports `useLocation` from `react-router`–is there something wrong with relying on the native API for getting the current path? I don't want to include react-router in our UI kit just to satisfy this single hook since routing libraries belong in the applications consuming the UI kit.

**To Reproduce**
Use `@cutting/svg` in a library *without* `react-router` specified in its manifest and attempt to use `ParentsizeSVG`.

**Expected behavior**
For the hook to not rely on a specific routing library's implementation for using the current window location/path.

**Screenshots**
N/A

**Applicable Versions:**
 - Browser version: N/A
 - Node.JS version:  `v16.4.2`

**Additional context**
Can answer any questions or provide more info if needed. Can also supply a PR if you're open to the change.

**Comment by dagda1** [comment]
@joeyfigaro thank you for raising this, and I've fixed this in #260 .

I've been meaning to remove react-router for some time.

I've just published a release:

- `@cutting/hooks@4.53.0`
- `@cutting/svg@4.50.1`
- `@cutting/use-get-parent-size@1.24.1`

Let me know if this fixes it.

**Comment by dagda1** [comment]
@joeyfigaro are you using `@cutting/svg` in a public repo?

**Comment by dagda1** [comment]
@joeyfigaro no reason, just curious.  I thought I was the only person that used it
