### ISSUE TITLE
Missing classnames dependency in react-typed-mousetrap

### ISSUE THREAD

**Issue by chmac** [dagda1/cuttingedge#8]
This package imports `classnames` here:

https://github.com/dagda1/cuttingedge/blob/4c367fbec143f1f556e4c221cc8ee8f11671da8c/packages/react-typed-mousetrap/src/components/Shortcuts/Shortcuts.tsx#L2

But it's not included in the dependencies here as far as I can see:

https://github.com/dagda1/cuttingedge/blob/4c367fbec143f1f556e4c221cc8ee8f11671da8c/packages/react-typed-mousetrap/package.json#L21-L26

Maybe it needs to be added? I ran `yarn add classnames` in my codebase and that fixed the error I was seeing.

**Comment by dagda1** [comment]
@chmac thanks for this.  I had no idea anybody else would ever use it

**Comment by chmac** [comment]
Looks like >600 downloads a month! https://yarnpkg.com/?q=react-typed-mouse&p=1
