### ISSUE TITLE
Uncaught SyntaxError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by RodeoAdrian** [dagda1/cuttingedge#86]
**Describe the bug**
Trying to implement the package on a clean create-react-app:

*App.js*
```javascript
import React, { useRef } from 'react';
import './App.css';
import logo from './logo.svg';
import { ParentsizeSVG } from '@cutting/svg';

function App() {
  const ref = useRef(null)
  
  return (
    <div className="App" ref={ref}>
      <span>SVG</span>
      <ParentsizeSVG ref={ref}>
        <rect
          x="20%"
          y="20%"
          width={'50%'}
          height={'50%'}
          rx="20"
          style={{ fill: '#ff0000', stroke: '#000000', strokeWidth: '2px' }}
        />
      </ParentsizeSVG>
    </div>
  );
}

export default App;
```

I'm getting `Uncaught SyntaxError: Invalid left-hand side in assignment`

**To Reproduce**

1. `npx create-react-app responsive-svg`
2. `npm install @cutting/svg`
3.  Replace App.js content inside `src/App.js` with code above
4.  npm run start
5.  go to http://localhost:3000/
6. Blank page. see console error

**Expected behavior**
Render without errors the basic usage example for this package

**Applicable Versions:**
 - Browser version: Chome 99.0.4844.84
 - Node.JS version: v16.14.0

**Comment by dagda1** [comment]
@RodeoAdrian thank you for the bug report.  I'll take a look now
